services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    restart: unless-stopped

    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console

    environment:
      RUSTFS_ADDRESS: "0.0.0.0:9000"
      RUSTFS_CONSOLE_ADDRESS: "0.0.0.0:9001"
      RUSTFS_CONSOLE_ENABLE: "true"

      RUSTFS_ACCESS_KEY: "rustfsadmin"
      RUSTFS_SECRET_KEY: "rustfsadmin123"

      RUSTFS_VOLUMES: "/data"

    volumes:
      - rustfs_data:/data

  liteparse:
    image: ghcr.io/run-llama/liteparse-server:main
    container_name: liteparse
    ports:
      - "5707:5707"

volumes:
  rustfs_data: