
services:

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    env_file:
      - .env
    ports:
      - "8000:8000"


  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ADDRESS: "0.0.0.0:9000"
      RUSTFS_CONSOLE_ADDRESS: "0.0.0.0:9001"
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_ACCESS_KEY: "${S3_ACCESS_KEY:?Set S3_ACCESS_KEY in .env}"
      RUSTFS_SECRET_KEY: "${S3_SECRET_KEY:?Set S3_SECRET_KEY in .env}"
      RUSTFS_VOLUMES: /data
    volumes:
      - rustfs_data:/data

  liteparse:
    image: ghcr.io/run-llama/liteparse-server:main
    ports:
      - "5707:5707"
    restart: unless-stopped


volumes:
  rustfs_data: